# Service synonyms for smart matching
SERVICE_SYNONYMS = {
    "lawn service": ["lawn mowing", "grass cutting", "lawn care", "grasscutters", "grass cutter", "grasscutting"],
    "software developer": ["software engineer", "developer", "programmer", "coder", "web developer", "frontend", "backend", "mobile", "android", "ios", "flutter", "react"],
    "plumber": ["pipe fixer", "plumbing service", "pipe repair", "pipe fitter"],
    "electrician": ["electrical repair", "electrical service", "electrician", "electric"],
    "cleaner": ["cleaning service", "house cleaning", "office cleaning", "maid", "janitor"],
    "driver": ["taxi", "chauffeur", "transport", "delivery driver"],
    "mechanic": ["car repair", "auto repair", "garage", "vehicle repair"],
    "painter": ["painting service", "house painter", "wall painting"],
    "carpenter": ["woodwork", "furniture maker", "woodwork service"],
    "gardener": ["landscaping", "garden service", "yard work"],
    "security": ["security guard", "protection service", "security service"],
    "tutor": ["teacher", "private tutor", "coaching", "lessons"],
    "hairdresser": ["hair stylist", "barber", "salon", "hair cutting"],
    "photographer": ["photo service", "event photographer", "studio photographer"],
    "caterer": ["food service", "event catering", "food delivery"],
    "welder": ["welding service", "metal work", "fabrication"],
    "tailor": ["sewing service", "clothing repair", "dressmaker"],
    "mason": ["bricklayer", "construction", "building work"],
    "roofer": ["roofing service", "roof repair", "roof installation"],
    "hvac": ["air conditioning", "heating", "ventilation", "ac service"],
    "pest control": ["exterminator", "fumigation", "pest removal"],
    "mover": ["moving service", "removals", "relocation", "transport"],
    "locksmith": ["lock service", "key cutting", "security locks"],
    "appliance repair": ["fridge repair", "washing machine repair", "tv repair", "electronics repair"],
    "event planner": ["party planner", "wedding planner", "event coordinator"],
    "personal trainer": ["fitness trainer", "gym instructor", "coach"],
    "nutritionist": ["dietitian", "food advisor", "nutrition advisor"],
    "accountant": ["bookkeeper", "tax preparer", "financial advisor"],
    "lawyer": ["attorney", "legal advisor", "legal service"],
    "real estate agent": ["property agent", "estate agent", "housing agent"],
    "insurance agent": ["insurance advisor", "policy agent", "coverage agent"],
    "web designer": ["ui designer", "ux designer", "website designer"],
    "graphic designer": ["designer", "visual designer", "creative designer"],
    "content writer": ["copywriter", "writer", "content creator"],
    "digital marketer": ["marketing expert", "seo specialist", "social media manager"],
    "consultant": ["advisor", "specialist", "expert consultant"],
}
